networks:
  kine_network:
    driver: bridge
    

services:
  api:
    container_name: kine-api
    build:
      context: ..
      dockerfile: docker/Dockerfile.api.yml
      target: development
    ports:
      - "3001:3001"
    restart: always
    environment:
      NODE_ENV: ${NODE_ENV}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_ACCESS_EXPIRES_IN: ${JWT_ACCESS_EXPIRES_IN}
      JWT_REFRESH_EXPIRES_IN: ${JWT_REFRESH_EXPIRES_IN}
    command: npm run seed
    depends_on:
      - postgres
    networks:
      - kine_network
  web:
    container_name: kine-web
    build:
      context: ..
      dockerfile: docker/Dockerfile.web.yml
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    ports:
      - "3000:3000"
    restart: always
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    working_dir: /app
    command: pnpm dev
    depends_on:
      - api



