networks:
  kine_network:
    driver: bridge
    

services:
  api:
    container_name: kine-api
    build:
      context: ..
      dockerfile: docker/Dockerfile.api.yml
      target: development
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: ${NODE_ENV}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_ACCESS_EXPIRES_IN: ${JWT_ACCESS_EXPIRES_IN}
      JWT_REFRESH_EXPIRES_IN: ${JWT_REFRESH_EXPIRES_IN}
    command: npm run seed
    depends_on:
      - postgres
    networks:
      - kine_network



